// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT818whbaA2adXMyovuBy5QtH0SZsSv0g',
    appId: '1:701472328034:android:9ff36a26cca798e2f8043b',
    messagingSenderId: '701472328034',
    projectId: 'blurt-3568a',
    storageBucket: 'blurt-3568a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGsCFWugfvYYIb1LetklnGEgiGwDPE6CI',
    appId: '1:701472328034:ios:fe78305f8cc2943bf8043b',
    messagingSenderId: '701472328034',
    projectId: 'blurt-3568a',
    storageBucket: 'blurt-3568a.firebasestorage.app',
    iosBundleId: 'com.example.blurt',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT818whbaA2adXMyovuBy5QtH0SZsSv0g',
    appId: '1:701472328034:android:9ff36a26cca798e2f8043b',
    messagingSenderId: '701472328034',
    projectId: 'blurt-3568a',
    storageBucket: 'blurt-3568a.firebasestorage.app',
    authDomain: 'blurt-3568a.firebaseapp.com',
  );
} 