// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtbvjsHuQWNvEDLQLvJKok5lwwVaKS2ro',
    appId: '1:701472328034:web:d171a7f85d037a27f8043b',
    messagingSenderId: '701472328034',
    projectId: 'blurt-3568a',
    authDomain: 'blurt-3568a.firebaseapp.com',
    storageBucket: 'blurt-3568a.firebasestorage.app',
    measurementId: 'G-J7Z0EPT7VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT818whbaA2adXMyovuBy5QtH0SZsSv0g',
    appId: '1:701472328034:android:9ff36a26cca798e2f8043b',
    messagingSenderId: '701472328034',
    projectId: 'blurt-3568a',
    storageBucket: 'blurt-3568a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGsCFWugfvYYIb1LetklnGEgiGwDPE6CI',
    appId: '1:701472328034:ios:fe78305f8cc2943bf8043b',
    messagingSenderId: '701472328034',
    projectId: 'blurt-3568a',
    storageBucket: 'blurt-3568a.firebasestorage.app',
    iosBundleId: 'com.example.blurt',
  );
}
